### ISSUE TITLE
File Metadata container way too small to fit all metadata

### ISSUE THREAD

**Issue by kz4** [VeloCloud/website-ui#67]
A lot of metadata is not visible and you have to scroll down to see it.

<img width="543" alt="screen shot 2017-04-25 at 2 23 14 pm" src="https://cloud.githubusercontent.com/assets/15188104/25401125/d81bd05c-29c2-11e7-9872-4d48e2e126cd.png">

**Comment by chtran14** [comment]
That is what the vertical scroll bar is for if you pull down the latest code and that's the preference for now. Plus with the metadata search box below it, it will be hard to make it bigger than needed. Another plus is we have the unlock button to resize the container you want. Thus that should resolve this issue :) since we want everything to fit nicely and that's the pay off.

**Comment by chtran14** [comment]
I will close this issue for now since Ian and others have agreed on the design. We can always change it bigger with the tools we have.

**Comment by kz4** [comment]
No, this part can be be expanded. Try it yourself before closing it

**Comment by chtran14** [comment]
We just did a demo about the whole site and everything is working and looking nicely. Thus we decide to keep it that way.

**Comment by kz4** [comment]
I mean it's okay you don't fix it now, but don't close it because it's a problem

**Comment by chtran14** [comment]
![image](https://cloud.githubusercontent.com/assets/22081743/25401974/355df978-29ac-11e7-8128-12b3b77e317d.png)
This is what I see with the scroll bar and you can use to to scroll down to see the stuff. Since the metadata search box is there, it will not be ideal to make it bigger as the resize tool is there for it.

**Comment by chtran14** [comment]
There's a trade off :) If we want a bigger size of file metadata, we have to reduce other stuff or move it around since there's a limit for what we can see for each container.

**Comment by chtran14** [comment]
Oh I see what you meant. You have to click on the unlock button first and use the tiny thing at the corner of that container and move/resize it as you want.

**Comment by chtran14** [comment]
This has been mentioned by Ian and other users and resolved since last night...do not remember what github issues it belong to but everything has been tested. I will close this for now. 
![image](https://cloud.githubusercontent.com/assets/22081743/25402254/fd0bb1fe-29ac-11e7-8217-b193535e79b4.png)

**Comment by kz4** [comment]
That's what I am saying, that's an enhancement, this shouldn't be closed until we implement it

**Comment by chtran14** [comment]
Cool. It's the user's reference as at this point, I will just leave that features like that since we do not know whether we want to keep the metadata search container or not, and what the actual users preference for this are. Plus as I said with the resize tool that we have, it should be enough. Whoever picks up this project later will know for sure that the users want :) That's the tradeoff in designing these features whether you want a neat/clean design or just a rough one where you cannot see everything but one thing can be seen clearly. Based on my work and UI experience, the one that we have right now is ideal for this class since we want to achieve something simple, neat and clean so that when we leave off this project, the person who picks it up will know how to changes things for their preference. Long story short, we can keep this open for the next group or if anyone wants to make more changes for it, go ahead :) as this feature design takes me a lot of efforts and time to pull off. Thank you

**Comment by chtran14** [comment]
I have another idea for it and have done some fix for it. Anyway, I will not push it back since Vy just deployed the new version. The pros is now you can completely move it around and make it full :) the cons is the scroll bar functionality will be lost as you need a fix height for it. 

![image](https://cloud.githubusercontent.com/assets/22081743/25409971/2ae5c1fc-29c9-11e7-8bd3-a356552d1e7f.png)

Either way is fine for me. Let me know if you like it that way so I can put comment on how to do it for the next team :)
